### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by PEMapModder** [LegendOfMCPE/Hormones#1]
For terminology, please refer to [the DOCS in the repo](../blob/master/DOCS.md)
- [ ] Hormones Plugin
  - [X] Lymph
    - [X] Upload server data to Heart
    - [X] Fetch latest server data from Heart
  - [x] Blood
    - [x] Create Hormone API
      - [x] Hormone registering and execution API
      - [X] Vein API
    - [x] Fetch latest hormones from Heart
- [ ] Extension plugins
  - [x] Mute/Ban system based on Hormones
  - [x] Kidney - a plugin/script for cleaning the Urea (outdated Hormones in the blood) in the blood (Don't blame me; I know that hormones won't turn into urea)

**Comment by iJoshuaHD** [comment]
is it just me who finds it disgusting? xD

**Comment by PEMapModder** [comment]
@iJoshuaHD I found nothing except your body disgusting :P

**Comment by PEMapModder** [comment]
The Artery part has been completed.

**Comment by Gamecrafter** [comment]
@PEMapModder What about tumors? >.<

**Comment by PEMapModder** [comment]
@Gamecrafter what tumours?

**Comment by jojoe77777** [comment]
May 2017 this message was edited

**Comment by Gamecrafter** [comment]
@PEMapModder What about ribosomes? <.<

**Comment by PEMapModder** [comment]
@Gamecrafter can you speak something meaningful, please?

**Comment by Gamecrafter** [comment]
@PEMapModder I'm giving suggestions on more "body" parts. Endoplasmic reticulums for the win! :smile:

**Comment by PEMapModder** [comment]
OK, so please explain what the body parts refer to.

**Comment by Gamecrafter** [comment]
a network of membranous tubules within the cytoplasm of a eukaryotic cell... => an item swapping system (I don't exactly know too, so don't blame me, this is a bit confusing)

**Comment by PEMapModder** [comment]
@Gamecrafter please start thinking from the plugin's perspective, not the biological perspective.

**Comment by Gamecrafter** [comment]
test

**Comment by ifvictr** [comment]
@PEMapModder Okay. At the moment I don't have any ideas, but when I do, I'll comment with it. :wink:

**Comment by dries-c** [comment]
mute and ban are working very well
i think you can check it off

**Comment by SOF3** [comment]
I forgot the existence of this list :P

**Comment by SOF3** [comment]
Not gonna use this list anyway. I prefer using issue list + milestones.
